version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: http-proxy-middleware
    versions:
    - 1.0.6
    - 1.1.0
    - 1.1.1
    - 1.1.2
    - 1.2.0
    - 1.3.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
    - 9.8.6
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: case-sensitive-paths-webpack-plugin
    versions:
    - 2.3.0
